ChatApp/ViewComponents/RoomViewComponent.cs
using ChatApp.Database;
using ChatApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;


namespace ChatApp.ViewComponents
{
    public class RoomViewComponent : ViewComponent
    {
        private AppDbContext _ctx;

        public RoomViewComponent(AppDbContext ctx)
        {
            _ctx = ctx;
        }

        public IViewComponentResult Invoke()
        {
            List<Chat> chats = new List<Chat>();

            if (HttpContext.User.Identity.IsAuthenticated)
            {
                string id = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
                chats = _ctx.ChatUsers
                    .Include(x => x.Chat)
                    .Where(x => x.UserId == id && x.Chat.Type == ChatType.Room)
                    .Select(x => x.Chat)
                    .ToList();

            }

            return View(chats);
        }
    }
}

ChatApp/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>ChatApp</title>
    <link rel="stylesheet" href="~/css/site.css">
</head>
<body>
    <div style="text-align:center" class="navbar">

        @if (!User.Identity.IsAuthenticated)
        {
            <h2>
                <a style="color: white; margin-left: 30px; text-decoration:none" href="/">ChatApp</a>
            </h2>
        }
        else
        {
            <h2>
                <a style="color: white; margin-left: 30px; text-decoration:none" href="/">ChatApp, Welcome @User.Identity.Name</a>
            </h2>
        }

    </div>

    <div class="navbar">
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="Home" asp-action="Find">Users</a>
        <a asp-controller="Account" asp-action="Logout">Logout</a>
    </div>

    <div class="main">

        @if (User.Identity.IsAuthenticated)
        {
            <vc:room></vc:room>
        }

        <div class="chat">
            @RenderBody()
        </div>
    </div>

    <div class="modal" id="create-room-modal">
        <form asp-controller="Home" asp-action="CreateRoom" class="modal-body">
            <header>Create Room</header>
            <div>
                <input name="name" />
            </div>
            <footer>
                <button>Create!</button>
                <button class="close" type="button" id="close-room">Close!</button>
            </footer>
        </form>
    </div>

    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>